apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  labels:
    app: crawler
spec:
  type: NodePort
  selector:
    app: crawler
  ports:
    - protocol: TCP
      name: http
      port: 9123
      targetPort: 9123